### ISSUE TITLE
Zero values mean everything, they should mean nothing

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/loggregator-api#12]
This was [covered in the SRE book](https://landing.google.com/sre/book/chapters/automation-at-google.html#xref_automation_diskerase-sidebar).

> Once upon a time, the automation in charge of decommissioning a particular rack failed, but only after the Diskerase step had completed successfully. Later, the decommission process was restarted from the beginning, to debug the failure. On that iteration, when trying to send the set of machines in the rack to Diskerase, the automation determined that the set of machines that still needed to be Diskerased was (correctly) empty. Unfortunately, the empty set was used as a special value, interpreted to mean "everything." This means the automation sent almost all the machines we have in all colos to Diskerase.

Zero values meaning "everything" can lead to disaster.

Currently, when making the following request:

```
&v2.EgressBatchRequest{}
```

You will get everything. This is bad. A similar request in a future v3 API should look like:

```
&v3.EgressBatchRequest{
	Selectors: []*v3.Selector{
		{
			Message: &v3.Selector_Everything{},
		},
	},
}
```

Using a sentinel value to explicitly ask for everything is a good idea. This should also apply to `SourceId` and anywhere else where zero values mean everything and not nothing. For instance to get all the logs:

```
&v3.EgressBatchRequest{
	Selectors: []*v3.Selector{
		{
			Message: &v3.Selector_Log{
				Log: &v3.LogSelector{
					Everything: true,
				},
			},
		},
	},
}
```

**Comment by poy** [comment]
This make quite a bit of sense. The selectors act as a white list anyways, so therefore if you don't include anything (and therefore do not whitelist anything) you should not get anything.

The only real consumers I'm aware of right now is [scalable-syslog](https://github.com/cloudfoundry/scalable-syslog) and [log-cache](https://github.com/cloudfoundry-incubator/log-cache). ScalableSyslog already includes selectors and log-cache is pre-GA. So in theory we could make the selectors required (do not egress anything if you don't include any) without too much concern.

However, this might be better suited for the v3 API. @ahevenor thoughts?

**Comment by bradylove** [comment]
Per conversation with @ahevenor. We will address this now for the `selectors` (and not `source_id`). V3 may take a different view of `source_id` all together.
