### ISSUE TITLE
Unused (and unwanted) query API

### ISSUE THREAD

**Issue by poy** [cloudfoundry/loggregator-api#13]
There are [egress query](https://github.com/cloudfoundry/loggregator-api/blob/master/v2/egress_query.proto) RPC methods that are unused. We are intending to have [LogCache](https://github.com/cloudfoundry-incubator/log-cache) fill the query void.

We should deprecated and remove these.

**Comment by bradylove** [comment]
Removed the egress query service in 4c9da50
