### ISSUE TITLE
Add an All selector

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/loggregator-api#17]
In issue #12 I brought up adding a selector called `Selector_Everything` that would allow a users of the RLP to get all data forwarded to them. Right now you must specify a selector for each type which is sort of a pain.

```go
req := loggregator_v2.EgressBatchRequest{
        Selectors: []loggregator_v2.Selector{
                {
                        Message: &loggregator_v2.Selector_Log{
                                Log: &loggregator_v2.LogSelector{},
                        },
                },
                {
                        Message: &loggregator_v2.Selector_Counter{
                                Counter: &loggregator_v2.CounterSelector{},
                        },
                },
                {
                        Message: &loggregator_v2.Selector_Gauge{
                                Gauge: &loggregator_v2.GaugeSelector{},
                        },
                },
                {
                        Message: &loggregator_v2.Selector_Timer{
                                Timer: &loggregator_v2.TimerSelector{},
                        },
                },
                {
                        Message: &loggregator_v2.Selector_Event{
                                Event: &loggregator_v2.EventSelector{},
                        },
                },
        },
}

```

`Selector_All` might be a better name, not sure.

**Comment by bradylove** [comment]
I do feel like this is verbose, however it is very explicit for those few times that you do actually want everything.

I do not see a real benefit in adding an `Everything` selector other than saving a few strokes of the keyboard. 

@ahevenor do you have any input on this?

**Comment by jasonkeene** [comment]
The semantics are different than what you described. An All selector would allow introduction of new envelope types on the server and clients would start getting that envelope data. If clients have to explicitly ask for each envelope type, along with being verbose, might not match the semantics of what they want. They would have to realize they are missing data and ship a code change to the client to start asking for that data. Adding new envelope types happens so infrequently however that it might not be worth doing.

**Comment by rroberts2222-zz** [comment]
No additional envelope types have been added in the past 4 years, so there isn't a huge concern of missing new envelope types. Based on the previous comments, this doesn't seem to have a huge benefit other than mitigating that concern, so I'm not sure if this is worth the effort to implement.
