### ISSUE TITLE
Converting v2 Gauge to v1 ValueMetric

### ISSUE THREAD

**Issue by evandbrown** [cloudfoundry/loggregator-api#20]
I'm working to convert v2 protos to v1, and the guide in the README has been helpful. For ValueMetric, the equivalent values in the v2 envelope all mention `first-key`. Does this indicate that the `Gauge.Metrics` map will only have one item in it, and that the item's key is the ValueMetric's name?

**Comment by bradylove** [comment]
@evandbrown sorry that table is not quite clear. When we convert a V2 Gauge metric into a V1 ValueMetric we actually create multiple V1 ValueMetric's. One ValueMetric for each of the Gauge metrics keys. You can see our own conversion for logic for V2 Gauges to V1 ValueMetrics [here](https://github.com/cloudfoundry/loggregator/blob/1a7410e5304eb27c7e7c158b96ec2054a79d558d/plumbing/conversion/tov1.go#L187-L215). 

Out of curiosity, why would you need to convert a V2 envelope to V1?

**Comment by bradylove** [comment]
Created #21 to hopefully make the README more clear.

**Comment by evandbrown** [comment]
This is super helpful! I'm moving Google's Stackdriver nozzle to use the v2 API so we get the benefits of deterministic routing (https://github.com/cloudfoundry-community/stackdriver-tools/issues/205). Converting to v1 on receipt seems like the simplest approach but I'd love your thoughts if there's a better way! Thanks so much for the quick response.

**Comment by bradylove** [comment]
Cool! I think converting V2 to V1 is an acceptable approach. One thing to keep an eye on would be CPU and Memory consumption of the conversion. We have had issues in the past with our conversion being fairly expensive.

Another thing I would point out is, in your V2 request to the RLP make sure you are setting `use_preferred_tags` to true. #19 plans to remove the deprecated tags and requesting preferred tags will prevent future breakage.

**Comment by poy** [comment]
Looks like this has been resolved. Closing.
