### ISSUE TITLE
Redundant and empty declaration

### ISSUE THREAD

**Issue by siennathesane** [cloudfoundry/loggregator-api#5]
Looking at the Egress API protobuf, I think the filtering feature is a little redundant, and filtering should probably be left up to an application.

```
service Egress {
  rpc Receiver(EgressRequest) returns (stream loggregator.v2.Envelope) {}
}

message EgressRequest {
  string shard_id = 1;
  Filter filter = 2;
}

message Filter {
  string source_id = 1;

  oneof Message {
    LogFilter log = 2;
  }
}

message LogFilter {
}
```

Should probably be:

```
service Egress {
  rpc Receiver(EgressRequest) returns (stream loggregator.v2.Envelope) {}
}

message EgressRequest {
  string shard_id = 1;
}
```

or something similar. The `LogFilter` doesn't do anything, and it's an essentially empty enum.

**Comment by hev** [comment]
We are including filtering based on feedback from lots of our API users. If you wish to do filtering in the application you can provide no filter to get all the data. Closing this issue.
